import { fileService } from '../fileService';
import type {
  BuildExecutionState,
  BuildExecutionStepSnapshot,
  BuildOutlineDraft,
  BuildTerminalSummary,
} from '../../types/chatBuild';

interface BuildMetaPayload {
  run_id: string;
  status: 'building' | 'completed' | 'failed' | 'interrupted';
  partial: boolean;
  outline_id: string;
  title: string;
  created_at: string;
  updated_at: string;
  build_root_path: string;
}

interface BuildStepPersistedPayload {
  id: string;
  name: string;
  summary: string;
  status: BuildExecutionStepSnapshot['status'];
  output_path: string | null;
  started_at: string | null;
  finished_at: string | null;
}

export interface BuildWriteTarget {
  runId: string;
  buildRootPath: string;
  metaPath: string;
  stepsPath: string;
  outlineId: string;
  createdAt: number;
  writtenRelativePaths: Set<string>;
}

function slugify(input: string): string {
  const normalized = input
    .trim()
    .toLowerCase()
    .replace(/[^a-z0-9\u4e00-\u9fa5]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48);

  return normalized || 'chat-build';
}

function iso(timestamp: number): string {
  return new Date(timestamp).toISOString();
}

function shortId(source: string): string {
  return source.replace(/[^a-zA-Z0-9]/g, '').slice(-6).toLowerCase() || 'build';
}

function stepFileName(index: number, step: BuildOutlineDraft['steps'][number]): string {
  return `${String(index + 1).padStart(2, '0')}-${slugify(step.name)}.md`;
}

function buildStepContent(
  outline: BuildOutlineDraft,
  step: BuildOutlineDraft['steps'][number],
  index: number,
): string {
  return [
    `# ${outline.title}`,
    '',
    `## Step ${index + 1}: ${step.name}`,
    '',
    `- Goal: ${outline.goal}`,
    `- Step Summary: ${step.summary}`,
    '',
    '## Generated Output',
    '',
    `This file is generated by Chat Build P1 real-run mode for the confirmed outline step "${step.name}".`,
    '',
    '## Notes',
    '',
    '- This resource was created inside a dedicated build root.',
    '- Existing workspace resources are not modified.',
    '- Future phases may replace this placeholder content with richer generated artifacts.',
    '',
  ].join('\n');
}

function buildMetaPayload(
  target: BuildWriteTarget,
  outline: BuildOutlineDraft,
  status: BuildMetaPayload['status'],
  partial: boolean,
  updatedAt: number,
): BuildMetaPayload {
  return {
    run_id: target.runId,
    status,
    partial,
    outline_id: target.outlineId,
    title: outline.title,
    created_at: iso(target.createdAt),
    updated_at: iso(updatedAt),
    build_root_path: target.buildRootPath,
  };
}

function buildStepsPayload(execution: BuildExecutionState): BuildStepPersistedPayload[] {
  return execution.steps.map((step) => ({
    id: step.id,
    name: step.name,
    summary: step.summary,
    status: step.status,
    output_path: step.outputPath ?? null,
    started_at: step.startedAt ? iso(step.startedAt) : null,
    finished_at: step.finishedAt ? iso(step.finishedAt) : null,
  }));
}

async function writeJson(path: string, payload: unknown) {
  await fileService.writeFile(path, `${JSON.stringify(payload, null, 2)}\n`);
}

async function ensureUniqueBuildRoot(workspacePath: string, seed: string): Promise<string> {
  for (let index = 0; index < 5; index += 1) {
    const suffix = index === 0 ? shortId(seed) : `${shortId(seed)}${index}`;
    const candidate = `${workspacePath}/${slugify(seed)}__build_${suffix}`;
    try {
      await fileService.createFolder(candidate);
      return candidate;
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      if (!message.includes('已存在')) {
        throw error;
      }
    }
  }

  throw new Error('无法创建唯一的 build root');
}

export const workspaceBuildWriter = {
  async createRun(workspacePath: string, outline: BuildOutlineDraft, runId: string): Promise<BuildWriteTarget> {
    const createdAt = Date.now();
    const buildRootPath = await ensureUniqueBuildRoot(workspacePath, outline.title || outline.goal || runId);
    const target: BuildWriteTarget = {
      runId,
      buildRootPath,
      metaPath: `${buildRootPath}/_build_meta.json`,
      stepsPath: `${buildRootPath}/_build_steps.json`,
      outlineId: `outline_${runId}`,
      createdAt,
      writtenRelativePaths: new Set(),
    };

    await writeJson(
      target.metaPath,
      buildMetaPayload(target, outline, 'building', false, createdAt),
    );
    await writeJson(
      target.stepsPath,
      outline.steps.map((step) => ({
        id: step.id,
        name: step.name,
        summary: step.summary,
        status: 'pending',
        output_path: null,
        started_at: null,
        finished_at: null,
      })),
    );

    return target;
  },

  async writeStep(
    target: BuildWriteTarget,
    outline: BuildOutlineDraft,
    execution: BuildExecutionState,
    step: BuildOutlineDraft['steps'][number],
    index: number,
  ): Promise<string> {
    const relativePath = stepFileName(index, step);
    if (target.writtenRelativePaths.has(relativePath)) {
      throw new Error(`步骤写入路径冲突: ${relativePath}`);
    }

    const fullPath = `${target.buildRootPath}/${relativePath}`;
    await fileService.writeFile(fullPath, buildStepContent(outline, step, index));
    target.writtenRelativePaths.add(relativePath);

    await writeJson(target.stepsPath, buildStepsPayload(execution));

    return fullPath;
  },

  async persistProgress(target: BuildWriteTarget, execution: BuildExecutionState) {
    await writeJson(target.stepsPath, buildStepsPayload(execution));
  },

  async finalize(
    target: BuildWriteTarget,
    outline: BuildOutlineDraft,
    execution: BuildExecutionState,
    terminal: BuildTerminalSummary,
  ) {
    const partial = terminal.kind !== 'completed';
    const status =
      terminal.kind === 'completed'
        ? 'completed'
        : terminal.kind === 'interrupted'
          ? 'interrupted'
          : 'failed';

    await writeJson(
      target.metaPath,
      buildMetaPayload(target, outline, status, partial, terminal.finishedAt),
    );
    await writeJson(target.stepsPath, buildStepsPayload(execution));
  },
};
